default:
  name: "MyBukkit"
  port: 25591
  password: "mypassword"
  bootstrap:
    - localhost:25590
  # --- Extra options ---
  # enabled: false # if you want to disable this socket
  # discovery: false # if you want to disable automatic connection to others sockets
  # timeout: 100 # delay between each message reading
  # debug: true # if you want to show every message in the console